### ISSUE TITLE
Can't install on Python 3.7 under linux

### ISSUE THREAD

**Issue by darribas** [GeoDaCenter/pygeoda#20]
I'd like to add `pygeoda` to the next iteration of the [`gds_env`](https://github.com/darribas/gds_env). I'm testing the install now but I don't think there are wheels for the linux-Python3.7 combination? This is what I get:

```shell
jovyan@ed8fee6d2e07:~$ pip install pygeoda==2
Collecting pygeoda==2
  ERROR: Could not find a version that satisfies the requirement pygeoda==2 (from versions: none)
ERROR: No matching distribution found for pygeoda==2
jovyan@ed8fee6d2e07:~$
```

This is under a container based on the [`minimal-notebook`](https://hub.docker.com/r/jupyter/minimal-notebook) image, so running bionic, and with:

```
pip                       19.2.1                   py37_0    conda-forge
python                    3.7.3                h33d41f4_1    conda-forge
```

Am I missing something? If not, is adding this in the roadmap?

Thanks very much!

**Comment by lixun910** [comment]
@darribas  Hi Dani, pygeoda is at a very early stage: the currently available version is 0.0.3. Can you try pip install pygeoda? https://pypi.org/project/pygeoda/#files   or do you mean PySAL==2? 

Documentation: https://lixun910.github.io/pygeoda/
mybinder notebooks:  https://mybinder.org/v2/gh/lixun910/pygeoda_tutorial/v0.0.3

Let me know about any issues. Thanks! 

Xun

**Comment by darribas** [comment]
Sorry, I should've been a bit more specific. I did `pip install pygeoda==2` since I knew that'd fail but it'd show me the versions available (it's a version of [this](https://stackoverflow.com/questions/4888027/python-and-pip-list-all-versions-of-a-package-thats-available#26664162)). The error remains if I just `pip install pygeoda` on Bionic and Python 3.7. There's no rush, but I just wanted to flag it.

**Comment by lixun910** [comment]
@darribas  Yes, I checked the wheel for bionic and python 3.7 is not in pypi page, and I just create one using the current v0.0.4 branch. It will be a little different, but you should be able to install it now using: pip install pygeoda==0.0.3 on Bionic and Python 3.7. 

Let me know any questions. Thanks!

Xun

**Comment by darribas** [comment]
Fantastic!!! I'll give it a try and report! To be sure, is this v0.0.3 or the current 0.0.4? Thanks very much Xun!!!

**Comment by lixun910** [comment]
You are welcome, @darribas ! It's v0.0.3 (which is based on current working branch -- the previous libgeoda v0.0.3 doesn't exist anymore)

**Comment by darribas** [comment]
Excellent! I'll close now as this has been fixed!
